### ISSUE TITLE
Only use local Installation and never global Installation

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/node-osrm#235]
When running `make test`, the state of the system currently influences the result.

I had a local installation that was build with BOOST 1.6.1. Running `make test` failed with 
```
*** Using osrm-extract from /usr/local/bin/osrm-extract ***
Running osrm-extract...
dyld: Symbol not found: __ZNK5boost16re_detail_10600031cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_
  Referenced from: /usr/local/bin/osrm-extract
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
 in /usr/local/bin/osrm-extract
/bin/sh: line 1: 10591 Trace/BPT trap: 5       osrm-extract berlin-latest.osm.pbf -p car.lua
make[1]: *** [berlin-latest.osrm] Error 133
```
This error was resolved when uninstalling the global OSRM.
In our tests, we should only check for a local installation and not for a global installation, since we only want to check the local one.

What do you think @springmeyer ?

**Comment by TheMarex** [comment]
node-osrm needs to respect the global search path (or rather the current default search path) for binaries. This is needed in case you want to build against your already installed version of OSRM and not use the mason system to build a local version for node-osrm. I have used this in the past to quickly circle between changes in OSRM and node-osrm.

There might be documentation bug here using `source bootstrap.sh` before running `make test` should work.

`npm` has something to modify the search path of the current shell for convience (`npm link`), maybe it would be helpful if mason would have the same thing (or maybe it does?).

**Comment by springmeyer** [comment]
> When running make test, the state of the system currently influences the result.

Yes, this is by design, to enable you to use an externally installed/global osrm-backend per https://github.com/Project-OSRM/node-osrm#using-an-existing-local-osrm-backend.

To override this behavior (and be able to keep a global osrm-backend installation and have `make test` use the local instead) you would need to do:

```
export PATH=$(pwd)/mason_packages/.link/bin:$PATH
``` 

Then `which osrm-extract` should show the installed one over the local one.

**Comment by MoKob** [comment]
Hm. I have to say I don't agree with this setup. The default testing architecture for a project should test the project how it is, not an external dependency. Simply following the `release` documentation brings you to a failing state, if you have a working clone but an external dependency.

But I guess I can work around it.

**Comment by springmeyer** [comment]
@MoKob I agree and understand. Perhaps a better solution would be to make using an external osrm-backend opt-in more explicitly with a build option (rather than quietly via by having it on PATH). But when I think of trying to accomplish this I think we should just skip extra complexity like that and finish integrating node-osrm into osrm-backend instead.

**Comment by MoKob** [comment]
Well. From my understanding path architecture should work in a local first setting.
So `local directory` beats `usr/local` beats `/global` installation. I am unsure where these paths are set up, but my feeling is that they are added at the back instead of the front of the path. If they where added at the front, the normal set-up should just work out of the box.

**Comment by springmeyer** [comment]
Yes, pre-pending the local PATH would preference the local binaries over global. We could do this instead:

```
diff --git a/test/data/Makefile b/test/data/Makefile
index 217f2ce..0db4c5b 100755
--- a/test/data/Makefile
+++ b/test/data/Makefile
@@ -38,14 +38,14 @@ berlin-latest.osm.pbf:
 berlin-latest.osrm: berlin-latest.osm.pbf car.lua $(OSRM_EXTRACT)
        @echo "Verifiyng data file integrity..."
        node md5sum.js data.md5sum
-       @PATH="${PATH}:../../lib/binding" && echo "*** Using osrm-extract from `which osrm-extract` ***"
+       @PATH="../../lib/binding:${PATH}" && echo "*** Using osrm-extract from `which osrm-extract` ***"
        @echo "Running osrm-extract..."
-       @PATH="${PATH}:../../lib/binding" && osrm-extract berlin-latest.osm.pbf -p car.lua
+       @PATH="../../lib/binding:${PATH}" && osrm-extract berlin-latest.osm.pbf -p car.lua
 
 berlin-latest.osrm.hsgr: berlin-latest.osrm car.lua $(OSRM_CONTRACT)
-       @PATH="${PATH}:../../lib/binding" && echo "*** Using osrm-contract from `which osrm-contract` ***"
+       @PATH="../../lib/binding:${PATH}" && echo "*** Using osrm-contract from `which osrm-contract` ***"
        @echo "Running osrm-contract..."
-       @PATH="${PATH}:../../lib/binding" && osrm-contract berlin-latest.osrm
+       @PATH="../../lib/binding:${PATH}" && osrm-contract berlin-latest.osrm
 
 checksum:
        md5sum lib/access.lua lib/destination.lua car.lua berlin-latest.osm.pbf > data.md5sum
```

**Comment by springmeyer** [comment]
Implementing @MoKob's suggestion in #255. Closing this, will track at #255
